### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by bq1024** [bnb-chain/greenfield-storage-provider#301]
Need some help to build from source.
```
$ go version
go version go1.19.6 linux/amd64

$ make build
bash +x ./build.sh
./build.sh: line 12: buf: command not found
service/challenge/challenge.go:15:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/challenge/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/challenge/types
service/downloader/downloader.go:15:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/downloader/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/downloader/types
service/metadata/client/metadata_client.go:10:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/metadata/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/metadata/types
service/p2p/p2p.go:19:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/p2p/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/p2p/types
service/receiver/client/receiver_client.go:10:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/receiver/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/receiver/types
service/signer/client/signer_client.go:13:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/signer/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/signer/types
service/tasknode/task_node.go:19:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/tasknode/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/tasknode/types
store/sqldb/database.go:7:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/types
service/uploader/client/uploader_client.go:11:2: no required module provides package github.com/bnb-chain/greenfield-storage-provider/service/uploader/types; to add it:
	go get github.com/bnb-chain/greenfield-storage-provider/service/uploader/types
build failed Ooooooh!!!
```

**Comment by will-2012** [comment]
1. Execute `go install github.com/bufbuild/buf/cmd/buf@v1.13.1`
2. Execute `buf` and observe whether there is an error?

**Comment by bq1024** [comment]
> Looks like it can't find `buf`, you can:
> 
> 1. Execute `go install github.com/bufbuild/buf/cmd/buf@v1.13.1`
> 2. Execute `buf` and observe whether there is an error?

$ go install github.com/bufbuild/buf/cmd/buf@v1.13.1
$ buf

Command 'buf' not found, did you mean:

  command 'bmf' from deb bmf (0.9.4-10)
  command 'bus' from deb atm-tools (1:2.5.1-4)
  command 'bf' from deb bf (20041219ubuntu6)
  command 'puf' from deb puf (1.0.0-7build1)

Try: sudo apt install <deb name>

**Comment by will-2012** [comment]
It is the `bufbuild`, refer to https://buf.build/docs/installation/.

**Comment by ZiyuanStar** [comment]
> > Looks like it can't find `buf`, you can:
> > 
> > 1. Execute `go install github.com/bufbuild/buf/cmd/buf@v1.13.1`
> > 2. Execute `buf` and observe whether there is an error?
> 
> $ go install github.com/bufbuild/buf/cmd/buf@v1.13.1 $ buf
> 
> Command 'buf' not found, did you mean:
> 
> command 'bmf' from deb bmf (0.9.4-10) command 'bus' from deb atm-tools (1:2.5.1-4) command 'bf' from deb bf (20041219ubuntu6) command 'puf' from deb puf (1.0.0-7build1)
> 
> Try: sudo apt install

try this:
GO111MODULE=on GOBIN=/usr/local/bin go install \
github.com/bufbuild/buf/cmd/buf@v1.17.0
buf --version

**Comment by bq1024** [comment]
> > > Looks like it can't find `buf`, you can:
> > > 
> > > 1. Execute `go install github.com/bufbuild/buf/cmd/buf@v1.13.1`
> > > 2. Execute `buf` and observe whether there is an error?
> > 
> > 
> > $ go install github.com/bufbuild/buf/cmd/buf@v1.13.1 $ buf
> > Command 'buf' not found, did you mean:
> > command 'bmf' from deb bmf (0.9.4-10) command 'bus' from deb atm-tools (1:2.5.1-4) command 'bf' from deb bf (20041219ubuntu6) command 'puf' from deb puf (1.0.0-7build1)
> > Try: sudo apt install
> 
> try this: GO111MODULE=on GOBIN=/usr/local/bin go install github.com/bufbuild/buf/cmd/buf@v1.17.0 buf --version

Thanks! This works.
But there's another issue here, looks like `go install github.com/gogo/protobuf/protoc-gen-gogofaster@latest` doesn't work
```
$ make build
bash +x ./build.sh
Failure: plugin gogofaster: could not find protoc plugin for name gogofaster - please make sure protoc-gen-gogofaster is installed and present on your $PATH
```

**Comment by bq1024** [comment]
Fixed it with 
`GO111MODULE=on GOBIN=/usr/local/bin go install github.com/gogo/protobuf/protoc-gen-gogofaster@latest`

$ ./gnfd-sp version
Greenfield Storage Provider
    __                                                       _     __
    _____/ /_____  _________ _____ ____     ____  _________ _   __(_)___/ /__  _____
    / ___/ __/ __ \/ ___/ __  / __  / _ \   / __ \/ ___/ __ \ | / / / __  / _ \/ ___/
    (__  ) /_/ /_/ / /  / /_/ / /_/ /  __/  / /_/ / /  / /_/ / |/ / / /_/ /  __/ /
    /____/\__/\____/_/   \__,_/\__, /\___/  / .___/_/   \____/|___/_/\__,_/\___/_/
    /____/       /_/
    
Version : v0.1.0-fix
Branch  : master
Commit  : c94f38e817ced713f390a46201f9fa73688bc83d
Build   : go1.19.6 linux amd64 2023-04-12 01:50


Thanks! Closing this issue now
