### ISSUE TITLE
no good addresses

### ISSUE THREAD

**Issue by flyhxg** [bnb-chain/greenfield-storage-provider#366]
Hello, may I ask what the problem is? "Error": "no good addresses
![1682233449574](https://user-images.githubusercontent.com/11693167/233825113-c8163270-f069-4b22-b2b0-5f7796471d18.png)

**Comment by kris-ss** [comment]
Hello, can you check your logs please? Does it still show the same "error":"no good addresses" messages?

**Comment by flyhxg** [comment]
Yes, the screenshot shows the logs

**Comment by kris-ss** [comment]
@flyhxg 

Can you share your start-up command please. And which build are you using?

**Comment by flyhxg** [comment]
![1682296691863](https://user-images.githubusercontent.com/11693167/233876054-206a091f-606d-4986-8e9b-e78fbc072100.png)
Please take a look.

**Comment by flyhxg** [comment]
Please take a look.

![1682296747066](https://user-images.githubusercontent.com/11693167/233876123-b69af131-9774-438c-9550-780cd3f4e4e8.png)

**Comment by flyhxg** [comment]
> Please take a look.
> 
> ![1682296747066](https://user-images.githubusercontent.com/11693167/233876123-b69af131-9774-438c-9550-780cd3f4e4e8.png)

![1682296868576](https://user-images.githubusercontent.com/11693167/233876224-4691c0ff-8862-44c5-bd10-e7759713b0ce.png)
This config.toml

**Comment by joeylichang** [comment]
How to config the 'P2PCfg.Bootstrap' field?
```
[P2PCfg]
ListenAddress = "127.0.0.1:9933"
# p2p node msg Secp256k1 encryption key, it is different from other SP's addresses
P2PPrivateKey = ""
# p2p node's bootstrap node, format: [node_id1@ip1:port1, node_id2@ip1:port2]
Bootstrap = []
```

**Comment by kris-ss** [comment]
@joeylichang  @flyhxg 

You can use below bootstrap setting in [P2PCfg]

Bootstrap = ["16Uiu2HAkvgrSt4oUNZ8rWe2qpimLDajyqD6Ca7LV7n9FkzzPNDQh@k8s-gftestne-p2pexter-bc25ac70bc-a31e9596d87054c3.elb.us-east-1.amazonaws.com:9933"]

**Comment by flyhxg** [comment]
> @joeylichang @flyhxg
> 
> You can use below bootstrap setting in [P2PCfg]
> 
> Bootstrap = ["[16Uiu2HAkvgrSt4oUNZ8rWe2qpimLDajyqD6Ca7LV7n9FkzzPNDQh@k8s-gftestne-p2pexter-bc25ac70bc-a31e9596d87054c3.elb.us-east-1.amazonaws.com](mailto:16Uiu2HAkvgrSt4oUNZ8rWe2qpimLDajyqD6Ca7LV7n9FkzzPNDQh@k8s-gftestne-p2pexter-bc25ac70bc-a31e9596d87054c3.elb.us-east-1.amazonaws.com):9933"]

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/11693167/235030137-e9613d36-7fea-4c14-a904-62905151ff54.png">
This still indicates this error

**Comment by joeylichang** [comment]
> 
```
[P2PCfg]
ListenAddress = "127.0.0.1:9833"  // the p2p protocol listen address
P2PPrivateKey = ""
Bootstrap = []
PingPeriod = 2 // p2p ping other sp p2p node period
```
P2PPrivateKey generate method
`./gnfd-sp  p2p.create.key -n=1`
the result:
`0 private key: 8cc170a45e77558974f9069af0a66b6bd223926cbc2614cb112183ce0e0d3a39` --> the private key
`0 node id key: 16Uiu2HAmAJ6EcBfxgiFFTKCMS6zCPeDdikrLGQrDXVKPbMyz6nYB` -->  nodeid corresponding to the 

Bootstrap
Bootstrap is already online SP infomation
It's format = nodeid@address

Bootstrap = ["[16Uiu2HAkvgrSt4oUNZ8rWe2qpimLDajyqD6Ca7LV7n9FkzzPNDQh@k8s-gftestne-p2pexter-bc25ac70bc-a31e9596d87054c3.elb.us-east-1.amazonaws.com]

**Comment by joeylichang** [comment]
> Does PSP need to hand over private key as well, not just the address to their SP node address ?
> 
> I can see how this is testing secondary SP, since a master Amazon node is storing information from multiple SP.
> 
> What is happening here that's blocking an SP from uploading to a client it doesn't own?

There is no need to expose P2P private key, but his nodeID (generated by public key) needs to be exposed to others, and the encryption of user information interaction is required.

The P2P protocol is used as a method of probing between SPs. It will ensure that a better node is selected as the secondary. Of course, the secondary sp can also reject the replicate data approval request sent by the primary.

**Comment by fys05** [comment]
I also encountered the same problem. Did you solve it, can you share it?

**Comment by joeylichang** [comment]
P2P will cache the old node information (using a conservative deletion method, see: [Customized ping service](https://github.com/bnb-chain/greenfield-storage-provider/blob/master/modular/p2p/p2pnode/node.go#L104), [PeerProvider](https://github.com/bnb-chain/greenfield-storage-provider/blob/master/modular/p2p/p2pnode/peers.go#L62) ), the error "no good addresses" is mainly due to the invalid nodes (such as multiple restarts, the previous node information is not deleted in time by other SPs , there will be this error), but as long as a sufficient number of SP (P2P) nodes are used to synchronize data between the primary and secondary. This error has been removed in the new version.
