### ISSUE TITLE
Provide the API version in an endpoint

### ISSUE THREAD

**Issue by urbanogt** [bnb-chain/greenfield-storage-provider#424]
It would be great if you provide a get_info endpoint where you get the API version and maybe other data.

Use case:
- You have a library/SDK compatible with v0.1.0 and the node gets updated to v0.1.2. The SDK that connects to the v0.1.2 should present a warning or directly not work on the new version.

**Comment by will-2012** [comment]
Very good suggestion, the team will add related interfaces.
